Assignment-1: NumPy
6 NumPy Coding Problems

In [12]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
vector=np.full((10),np.NaN)
print(vector)
print(vector.size)
vector[4]=1
print(vector)


[nan nan nan nan nan nan nan nan nan nan]
10
[nan nan nan nan  1. nan nan nan nan nan]


In [13]:
# 2. Create a vector with values ranging from 10 to 49.
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [24]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
vector=np.array([1,2,0,0,4,0])
np.where(vector!=0)

(array([0, 1, 4], dtype=int64),)

In [23]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
matrix=np.random.randint(100,size=(10,10))
print(matrix)
print(np.min(matrix))
print(np.max(matrix))

[[30 97  2  2 58 64 81  8 30 86]
 [20 78 53 23 22 96  5 97 43 67]
 [57 22 53 68 15  3 36 41 38 33]
 [13 99 98 88 82 71 58  1 32 93]
 [16 97 13 69 82 21 16 63 51 44]
 [ 0 78 23 63 95 18 77 17 98 65]
 [27 47 58  3 38 44 68 12 55 74]
 [56 43 28 22 57 71 31 40 82 19]
 [ 0 34 22 13 17 88 75 50 83 68]
 [15  9 31 65 52 16 59 94 91 50]]
0
99


In [28]:
# 6. Create a random vector of size 30 and find the mean value.
vector=np.random.randint(100,size=(30))
print(vector)
print(np.mean(vector))


[ 3 30 44 62  4 26 28 72 73 51 75 21  0 77 39 92 19 71 68 12 21 98 25 17
  6 23 94 29 36  2]
40.6
